# Change these first
owner: ihatenodejs # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository 

sites:
  - name: Mail Server
    url: https://user.p0ntus.com
  - name: Mail Server Dashboard
    url: https://mail.p0ntus.com
  - name: Vaultwarden
    url: https://vaultwarden.p0ntus.com
  - name: Archive Website
    url: https://p0ntus.com
  - name: Main Website
    url: https://aidxn.fun
  - name: Retro Main Website
    url: https://old.aidxn.fun

status-website:
  cname: status.p0ntus.com
  logoUrl: https://raw.githubusercontent.com/ihatenodejs/ihatenodejs/refs/heads/main/aidan.jpeg
  name: p0ntus monitor
  introTitle: "welcome to **p0ntus monitor**"
  introMessage: p0ntus monitor watches the status of several of my services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
